
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-organic-f23-6pm-3
owner: ucsb-cs156-f23
repo_name: proj-organic-f23-6pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjcwMzQxMDg0","is_bot":false,"login":"Garrett-Hu","name":""},"headRefName":"Garrett-CoursesEditPage2","number":36,"title":"CRUD Operations F3 - Edit Page","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-3/pull/36"},{"author":{"id":"U_kgDOBsEUwg","is_bot":false,"login":"SalvadorGracia","name":""},"headRefName":"Salvador-BackendInterceptors","number":34,"title":"Added Interceptor and Test","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-3/pull/34"},{"author":{"id":"U_kgDOB7-lTA","is_bot":false,"login":"YicongYan","name":""},"headRefName":"Yicong-CourseController-DELETE","number":33,"title":"CRUD Operations B2 - DELETE and Controllers","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-3/pull/33"},{"author":{"id":"U_kgDOB7-lTA","is_bot":false,"login":"YicongYan","name":""},"headRefName":"Yicong-CourseController-PUT","number":27,"title":"CRUD Operations B2 - PUT and Controllers","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-3/pull/27"},{"author":{"id":"MDQ6VXNlcjg4MjMzMDc2","is_bot":false,"login":"HououinKyouma-2036","name":"HououinKyouma-2036"},"headRefName":"Leo-CourseController-GETbyID","number":25,"title":"CRUD Operations B1 - POST/GET and Controllers","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-3/pull/25"},{"author":{"id":"U_kgDOBXqLzw","is_bot":false,"login":"erica-ll","name":"Erica Liu"},"headRefName":"Erica-F1-UserTable","number":18,"title":"Add toggle-admin and toggle-instructor columns in UsersTable","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-3/pull/18"}]
