
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-organic-f23-6pm-3
owner: ucsb-cs156-f23
repo_name: proj-organic-f23-6pm-3
pull_requests: [{"author":{"id":"U_kgDOBsEUwg","is_bot":false,"login":"SalvadorGracia","name":""},"headRefName":"Salvador-CourseForm","number":24,"title":"Course Form and Tests","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-3/pull/24"},{"author":{"id":"U_kgDOBXqLzw","is_bot":false,"login":"erica-ll","name":"Erica Liu"},"headRefName":"Erica-F1-UserTable","number":18,"title":"Add toggle-admin and toggle-instructor columns in UsersTable","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-3/pull/18"}]
